VERSION = "LT_20220217_001"
mp4_extends = '*.mp4'
gif_extends = '*.gif'
SIZE_MB = 1024*1024
FileFolder = '/home/venom/Videos/Demo_Video/'
#ThumbnailFileFolder = '/home/jason/Videos/Demo_Video/.thumbnail/'
title = 'LED Test Web App'
ThumbnailFileFolder = '.thumbnail/'
flask_server_port = 9090
broadcast_port = 5000
scale_fit_ori_ratio = False
horizontal_display = True

led_total_width = 80
led_total_height = 12
led_area_startx = 0
led_area_starty = 0
led_area_width = 10
led_area_height = 10