# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 371, 441))
        self.groupBox.setObjectName("groupBox")
        self.radioButton_color_red = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_color_red.setGeometry(QtCore.QRect(30, 50, 99, 21))
        self.radioButton_color_red.setObjectName("radioButton_color_red")
        self.radioButton_color_green = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_color_green.setGeometry(QtCore.QRect(30, 90, 99, 21))
        self.radioButton_color_green.setObjectName("radioButton_color_green")
        self.radioButton_color_blue = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_color_blue.setGeometry(QtCore.QRect(30, 130, 99, 21))
        self.radioButton_color_blue.setObjectName("radioButton_color_blue")
        self.radioButton_color_white = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_color_white.setGeometry(QtCore.QRect(30, 170, 99, 21))
        self.radioButton_color_white.setObjectName("radioButton_color_white")
        self.verticalSlider = QtWidgets.QSlider(self.groupBox)
        self.verticalSlider.setGeometry(QtCore.QRect(230, 39, 20, 381))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.textEdit_ledbrilevel = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_ledbrilevel.setGeometry(QtCore.QRect(40, 360, 104, 31))
        self.textEdit_ledbrilevel.setObjectName("textEdit_ledbrilevel")
        self.label_ledbrilevel = QtWidgets.QLabel(self.groupBox)
        self.label_ledbrilevel.setGeometry(QtCore.QRect(40, 320, 141, 31))
        self.label_ledbrilevel.setObjectName("label_ledbrilevel")
        self.label_slider_value = QtWidgets.QLabel(self.groupBox)
        self.label_slider_value.setGeometry(QtCore.QRect(260, 200, 57, 51))
        self.label_slider_value.setText("")
        self.label_slider_value.setObjectName("label_slider_value")
        self.label_pico_num = QtWidgets.QLabel(self.centralwidget)
        self.label_pico_num.setGeometry(QtCore.QRect(430, 50, 171, 21))
        self.label_pico_num.setObjectName("label_pico_num")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(420, 150, 211, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_all = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_all.setGeometry(QtCore.QRect(30, 50, 99, 21))
        self.radioButton_all.setObjectName("radioButton_all")
        self.radioButton_single = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_single.setGeometry(QtCore.QRect(30, 90, 99, 21))
        self.radioButton_single.setObjectName("radioButton_single")
        self.textEdit_led_single = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_led_single.setGeometry(QtCore.QRect(30, 120, 101, 31))
        self.textEdit_led_single.setObjectName("textEdit_led_single")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LED_1111_Controller"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.radioButton_color_red.setText(_translate("MainWindow", "Red"))
        self.radioButton_color_green.setText(_translate("MainWindow", "Green"))
        self.radioButton_color_blue.setText(_translate("MainWindow", "Blue"))
        self.radioButton_color_white.setText(_translate("MainWindow", "White"))
        self.label_ledbrilevel.setText(_translate("MainWindow", "LED Brightness Level"))
        self.label_pico_num.setText(_translate("MainWindow", "Zero controller online"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.radioButton_all.setText(_translate("MainWindow", "ALL"))
        self.radioButton_single.setText(_translate("MainWindow", "Single"))
